import Vue from 'vue'
import { Button, Form, FormItem, Input ,Container ,Header,Aside,Main,Tabs,Avatar,
         Menu,MenuItem,Submenu,MenuItemGroup,ButtonGroup,Tooltip,Dropdown,DropdownItem,
         DropdownMenu,TabPane,Row,Col,Image,Card,Table,TableColumn,Progress,Breadcrumb,BreadcrumbItem} from 'element-ui'
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Tabs)
Vue.use(Avatar)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(ButtonGroup)
Vue.use(Button)
Vue.use(Tooltip)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Dropdown)
Vue.use(TabPane)
Vue.use(Row)
Vue.use(Col)
Vue.use(Card)
Vue.use(Image)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Progress)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
